# Generated by Django 4.0.4 on 2022-05-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota_Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('Num_NF', models.IntegerField()),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
