# Generated by Django 4.0.4 on 2022-05-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_cargo_colaborador_folha_pag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
