# Generated by Django 4.0.4 on 2022-05-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_delete_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
    ]
