# Generated by Django 4.0.4 on 2022-05-15 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rh.cargo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rh.departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='folha_pag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rh.folha_pag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota_fiscal',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rh.departamento'),
            preserve_default=False,
        ),
    ]
